ThalesGroup/CipherTrust_Application_Protection

crypto/csharp/README.md
key_management/csharp/README.md

Update readme file

---

pkcs11/VAE/csharp/Program.cs
pkcs11/VAE/csharp/README.md

Update the README file and sample's usage section.

Update README.md and usage function.[CAP-1415]

---

crypto/C/CryptoSinglePart_Fast.c
kmip/C/KMIPCrypto.c
kmip/C/KMIPCrypto_AES_GCM.c
kmip/C/KMIPCrypto_RSA.c
kmip/C/KMIPGet.c

CADP|1325|1734 : changes in KMIP samples

---

pkcs11/C/README.md

CADP-1146: PKCS11 readme updated

---

pkcs11/C/pkcs11_sample_encrypt_decrypt.c
pkcs11/C/pkcs11_sample_key_states.c
pkcs11/C/pkcs11_sample_keypair_create_sign.c
pkcs11/C/pkcs11_sample_sign_verify.c

sample usage updated

---

certificate_management/C/NAECertificateManagement.c

Signed-off-by: t0262653 <105219876+t0262653@users.noreply.github.com>

Updating the sample to resolve memory leak

---

certificate_management/C/ReadMe.md
crypto/C/ReadMe.md
key_management/C/ReadMe.md
kmip/C/ReadMe.md

version removed for CADP for C

CADP-11780: version removed for CADP for C

---

Obfuscation/java/ObfuscationUtilitySample.java

updated sample with review comment

updated sample with review comment 

---

pkcs11/C/pkcs11_sample_attributes.c
pkcs11/C/pkcs11_sample_create_object.c
pkcs11/C/pkcs11_sample_encrypt_decrypt.c
pkcs11/C/pkcs11_sample_find_export_key.c
pkcs11/C/pkcs11_sample_helper.c
pkcs11/C/pkcs11_sample_import_key.c
pkcs11/C/pkcs11_sample_keypair_create_sign.c

Committing only samples which are required for CADP For C 8.14.0

[CADP-12818]: Committing samples required for 8.14 release only

---

crypto/csharp/README.md

updated .net version

---

key_management/csharp/README.md
miscellaneous/csharp/README.md

Cadp 13458: .net6 check

---

crypto/C/CryptoSinglePart_ExtHdrAll.c

CADP-14640: Corrected usage info

---

crypto/java/CachingSample.java

Update CachingSample.java for version key

---

pkcs11/C/pkcs11_sample_helper.c

Fixing for garbage value for deactivation time

[CADP-14440]: Fixing for garbage value

---

pkcs11/JAVA/README.md
pkcs11/JAVA/custom_wrapper/build.xml

CADP-16097 Chnaged jar version to 2.0

CADP-16097 Chnaged jar version to 2.0

---

pkcs11/C/fpe.h
pkcs11/C/pkcs11_sample_encrypt_decrypt.c
pkcs11/C/pkcs11_sample_helper.c
pkcs11/C/pkcs11_sample_helper.h

FF3-1 changes for PKCS11| Remote

FF3-1 changes for PKCS11| Remote

---

crypto/C/FPE/CryptoSinglePart_FPE.c
crypto/C/FPE/CryptoSinglePart_FPE_CC_SSN.c

CAPI changes for FF3-1

---

pkcs11/C/pkcs11_sample_encrypt_decrypt.c

[CADP-17582] Changes for FF3-1

[CADP-17582] Changes for FF3-1

---

pkcs11/C/fpe.h

Cadp 17567 : Updated fpe.h for FF3-1

---

pkcs11/C/pkcs11_sample_attributes.c
pkcs11/C/pkcs11_sample_helper.c
pkcs11/C/pkcs11_sample_helper.h

[CADP-17650]:Add support of public exponent for private key in sample

[CADP-17650]:Add support of public exponent for private key in sample

---

pkcs11/C/pkcs11_sample_encrypt_decrypt.c

UNICODE for FF3-1

---

pkcs11/csharp/CreateObjectSample.cs
pkcs11/csharp/KeypairSignSample.cs
pkcs11/csharp/Program.cs
pkcs11/csharp/README.md
pkcs11/csharp/Sample_Helpers.cs
pkcs11/csharp/TestAttributesSample.cs

update for CADP.NetCore EC Create, sign, verify, Test Attribute sample and sample bug fixes

CADP-16922: update for EC sample and sample bug fixes

---

pkcs11/C/pkcs11_sample_attributes.c
pkcs11/C/pkcs11_sample_helper.h

[CADP-19174] : Warnings removed

[CADP-19174] : Warnings removed

---

crypto/java/CachingSample.java
crypto/java/FPE/FPEEncryptionDecryptionSample.java
crypto/java/MultiThreadMacSample.java
crypto/java/MultiThreadSample.java

remove compilation issue and FPE update

Compilation issue cadp 16854

---

certificate_management/C/NAECertificateManagement.c
crypto/C/CryptoSinglePart_Fast.c
kmip/C/KMIPMisc.h
kmip/C/KMIPRevoke.c

RHEL8 Compilation warning fix

---

database/udf-trino-thales/.mvn/modernizer/violations.xml
database/udf-trino-thales/README.md
database/udf-trino-thales/notes
database/udf-trino-thales/pom.xml
database/udf-trino-thales/src/main/java/io/trino/plugin/thales/CustomLogger.java
database/udf-trino-thales/src/main/java/io/trino/plugin/thales/ThalesCADPFunctions.java
database/udf-trino-thales/src/main/java/io/trino/plugin/thales/ThalesPlugin.java

initial check in for trino udf cadp

add Trino/Starburst udf

---

pkcs11/C/pkcs11_sample_helper.c

This branch should be merged in 8.17 branch, before 8.17 merges to mater branch.

Correction for pkcs11_sample_helper.c

---

crypto/java/FPE/FPEEncryptionDecryptionEmailSample.java

Adding FPEEncryptionDecryptionEmailSample

Adding FPEEncryptionDecryptionEmailSample.java

---

miscellaneous/csharp/CryptoHeaderModuleSample.cs
miscellaneous/csharp/README.md

Added CryptoHeaderModule Sample

Added CryptoHeaderModule Sample

---

crypto/java/HMACSample.java
crypto/java/ProtectRevealBulkDataSample.java
crypto/java/ProtectRevealSample.java
crypto/java/ReprotectSample.java
crypto/java/SecretKeyEncryptionUsingRemoteKeystoreSample.java
tokenization/Date2/java/Date2TokenizeDetokenizeBulkDateSample.java
tokenization/Date2/java/Date2TokenizeDetokenizeSample.java

CADP-25288: Updating samples to latest

CADP-25288: Updating samples to latest

---

mcp-servers/thales-cdsp-crdp-mcp-server/LICENSE
mcp-servers/thales-cdsp-crdp-mcp-server/README.md
mcp-servers/thales-cdsp-crdp-mcp-server/docs/README.md
mcp-servers/thales-cdsp-crdp-mcp-server/docs/ai-assistants.md
mcp-servers/thales-cdsp-crdp-mcp-server/docs/prerequisites.md
mcp-servers/thales-cdsp-crdp-mcp-server/docs/testing.md
mcp-servers/thales-cdsp-crdp-mcp-server/n8n/README.md
mcp-servers/thales-cdsp-crdp-mcp-server/n8n/crdp_demo_mcp_client.json
mcp-servers/thales-cdsp-crdp-mcp-server/n8n/crdp_demo_mcp_server.json
mcp-servers/thales-cdsp-crdp-mcp-server/package.json
mcp-servers/thales-cdsp-crdp-mcp-server/scripts/test-server.js
mcp-servers/thales-cdsp-crdp-mcp-server/src/crdp-mcp-server.ts
mcp-servers/thales-cdsp-crdp-mcp-server/tsconfig.json

Add thales-cdsp-crdp-mcp-server
